Update - Thu May 25 2017 17:18:55 -04:00 (EDT)

diff --git a/.kdm/bashrc b/.kdm/bashrc
--- a/.kdm/bashrc
+++ b/.kdm/bashrc
@@ -1,7 +1,7 @@
 # kdm bash-env
 # .kdm/bashrc
 
-# Last modified : Fri 07 Apr 2017 01:44:39 PM EDT
+# Last modified : Thu 25 May 2017 05:11:31 PM EDT
 
 
 # Source global bashrc
@@ -177,90 +177,90 @@ output() {
 		# Below are special output formats
 
 		backtick) # Output the input string with backticks
-			local OUTPUT_FORMAT="${C_CODE}${C_BLD}\`%s\`${C_RST}\n"
-			;;
+		local OUTPUT_FORMAT="${C_CODE}${C_BLD}\`%s\`${C_RST}\n"
+		;;
 
-		error)
-			# Special function to output to stderr
-			local OUTPUT_STDERR="1>&2"
-			local OUTPUT_FORMAT="${C_RED_BRT_BLD}Error ${C_WHT_BRT}: ${C_RST}%s\n"
-			;;
+	error)
+		# Special function to output to stderr
+		local OUTPUT_STDERR="1>&2"
+		local OUTPUT_FORMAT="${C_RED_BRT_BLD}Error ${C_WHT_BRT}: ${C_RST}%s\n"
+		;;
 
-		failure)
-			# Special function for failure message, no string input
-			local COLOR_SELECTED="${C_RED_BRT_BLD}"
-			local OUTPUT_STRING="failure"
-			;;
+	failure)
+		# Special function for failure message, no string input
+		local COLOR_SELECTED="${C_RED_BRT_BLD}"
+		local OUTPUT_STRING="failure"
+		;;
 
-		keyval)
-			# Check for 2nd and 3rd args
-			if [[ -z "${2}" || -z "${3}" ]]; then
-				output usage "${USAGE_STRING}"
-				return
-			fi
-
-			local OUTPUT_FORMAT="${C_BLU}%s${C_WHT_BRT} : ${C_GRY}'${C_GRN}%s${C_GRY}'${C_RST}\n"
-
-			# Output special format and immediately return
-			printf "${OUTPUT_FORMAT}" "${2}" "${3}"
+	keyval)
+		# Check for 2nd and 3rd args
+		if [[ -z "${2}" || -z "${3}" ]]; then
+			output usage "${USAGE_STRING}"
 			return
-			;;
+		fi
 
-		leadup) # Special function for leadup to status message, no newline
-			# Create dot string and output format
-			printf -v LOADING_DOT_STRING '%*s' $((60-${#2}-${#3})) ''
-			local OUTPUT_FORMAT="${C_RST}Performing ${C_GRY}'${C_ORN_BRT}%s${C_GRY}'${C_RST} ${C_WHT_BRT}$(printf '%s' ${LOADING_DOT_STRING// /.}) ${C_RST}"
-			;;
+		local OUTPUT_FORMAT="${C_BLU}%s${C_WHT_BRT} : ${C_GRY}'${C_GRN}%s${C_GRY}'${C_RST}\n"
 
-		leadup-custom) # Special function for leadup to status message, no newline, with custom command name
-			# Check for 2nd and 3rd args
-			if [[ -z "${2}" || -z "${3}" ]]; then
-				output usage "${USAGE_STRING}"
-				return
-			fi
-
-			# Create dot string and output format
-			printf -v LOADING_DOT_STRING '%*s' $((60-${#2}-${#3})) ''
-			local OUTPUT_FORMAT="${C_RST}%s ${C_GRY}'${C_ORN_BRT}%s${C_GRY}'${C_RST} ${C_WHT_BRT}$(printf '%s' ${LOADING_DOT_STRING// /.}) ${C_RST}"
-
-			printf "${OUTPUT_FORMAT}" "${2}" "${3}"
-			return
-			;;
-
-		stderr)
-			# Special function to output to stderr
-			local COLOR_SELECTED="${C_BLU}"
-			local OUTPUT_STDERR="1>&2"
-			;;
-
-		success)
-			# Special function for success message, no string
-			local COLOR_SELECTED="${C_GRN_BRT_BLD}"
-			local OUTPUT_STRING="success"
-			;;
-
-		usage)
-			# Special function to output formatted usage string, with stderr output
-			local OUTPUT_FORMAT="${C_YLW_BRT_BLD}Usage ${C_WHT_BRT}: ${C_RST}%s\n"
-			local OUTPUT_STDERR="1>&2"
-			;;
-
-		*) local COLOR_SELECTED="${C_RST}";; # If nothing matches, reset color
-	esac
-
-	# Check for variables and throw usage message if issue
-	if [[ -z "${OUTPUT_STRING-${2}}" ]]; then
-		output usage "${USAGE_STRING}"
+		# Output special format and immediately return
+		printf "${OUTPUT_FORMAT}" "${2}" "${3}"
 		return
-	fi
+		;;
 
-	# Finalize vars
-	local OUTPUT_FORMAT="${OUTPUT_FORMAT-${COLOR_SELECTED}%s${C_RST}\n}"
-	local OUTPUT_STRING="${OUTPUT_STRING-${2}}"
+	leadup) # Special function for leadup to status message, no newline
+		# Create dot string and output format
+		printf -v LOADING_DOT_STRING '%*s' $((60-${#2}-${#3})) ''
+		local OUTPUT_FORMAT="${C_RST}Performing ${C_GRY}'${C_ORN_BRT}%s${C_GRY}'${C_RST} ${C_WHT_BRT}$(printf '%s' ${LOADING_DOT_STRING// /.}) ${C_RST}"
+		;;
 
-	# Output to stdout or stderr based on switch
-	[[ "${OUTPUT_STDERR}" ]] && printf "${OUTPUT_FORMAT}" "${OUTPUT_STRING}" 1>&2 && return
-	printf "${OUTPUT_FORMAT}" "${OUTPUT_STRING}"
+	leadup-custom) # Special function for leadup to status message, no newline, with custom command name
+		# Check for 2nd and 3rd args
+		if [[ -z "${2}" || -z "${3}" ]]; then
+			output usage "${USAGE_STRING}"
+			return
+		fi
+
+		# Create dot string and output format
+		printf -v LOADING_DOT_STRING '%*s' $((60-${#2}-${#3})) ''
+		local OUTPUT_FORMAT="${C_RST}%s ${C_GRY}'${C_ORN_BRT}%s${C_GRY}'${C_RST} ${C_WHT_BRT}$(printf '%s' ${LOADING_DOT_STRING// /.}) ${C_RST}"
+
+		printf "${OUTPUT_FORMAT}" "${2}" "${3}"
+		return
+		;;
+
+	stderr)
+		# Special function to output to stderr
+		local COLOR_SELECTED="${C_BLU}"
+		local OUTPUT_STDERR="1>&2"
+		;;
+
+	success)
+		# Special function for success message, no string
+		local COLOR_SELECTED="${C_GRN_BRT_BLD}"
+		local OUTPUT_STRING="success"
+		;;
+
+	usage)
+		# Special function to output formatted usage string, with stderr output
+		local OUTPUT_FORMAT="${C_YLW_BRT_BLD}Usage ${C_WHT_BRT}: ${C_RST}%s\n"
+		local OUTPUT_STDERR="1>&2"
+		;;
+
+	*) local COLOR_SELECTED="${C_RST}";; # If nothing matches, reset color
+esac
+
+# Check for variables and throw usage message if issue
+if [[ -z "${OUTPUT_STRING-${2}}" ]]; then
+	output usage "${USAGE_STRING}"
+	return
+fi
+
+# Finalize vars
+local OUTPUT_FORMAT="${OUTPUT_FORMAT-${COLOR_SELECTED}%s${C_RST}\n}"
+local OUTPUT_STRING="${OUTPUT_STRING-${2}}"
+
+# Output to stdout or stderr based on switch
+[[ "${OUTPUT_STDERR}" ]] && printf "${OUTPUT_FORMAT}" "${OUTPUT_STRING}" 1>&2 && return
+printf "${OUTPUT_FORMAT}" "${OUTPUT_STRING}"
 }
 
 #### Functions: Text ==final ####
@@ -842,17 +842,16 @@ _g_gpo() {
 			local SELECTED_BRANCH="postprod"
 			;;
 		*)
-			output usage "g-gpo <${USAGE_OPTIONS_STRING}> <${BRANCHES_STRING}>"
+			output usage "g-gpo <${USAGE_OPTIONS_STRING}> <${BRANCHES_STRING}> <-y>"
 			return
 	esac
 
 	output keyval "Pushing to branch" "${SELECTED_BRANCH}"
-	read -p "Continue? Enter Y/N: " GIT_PUSH_YN
-	echo
+	if [[ "${3##\-}" != [Yy] ]]; then
+		read -p "Continue? [Y/n] " GIT_PUSH_YN
+		echo
 
-	if [[ "${GIT_PUSH_YN}" != [Yy] ]]; then
-		output red "Push cancelled"
-		return 254
+		[[ "${GIT_PUSH_YN}" == [Nn] ]] && output red "Push cancelled" && return 254
 	fi
 
 	# Generate temp file for output (until I learn how to do it without that)
@@ -1284,12 +1283,9 @@ _fix_bash_pids() {
 				done
 				;;
 			kill)
-				read -p "Kill stale bash PIDs? Enter Y/N: " FIX_BASH_PIDS_YN
-
-				if [[ "${FIX_BASH_PIDS_YN}" != [Yy] ]]; then
-					output purple "No PIDs killed"
-					return
-				fi
+				read -p "Kill stale bash PIDs? [Y/n] " FIX_BASH_PIDS_YN
+				echo
+				[[ "${FIX_BASH_PIDS_YN}" == [Nn] ]] && output purple "No PIDs killed" && return false
 
 				for PID in ${FIX_BASH_PIDS_PID_LIST[@]}; do
 					output yellow "Killing PID ${PID}"
@@ -1332,10 +1328,9 @@ _fix_macos_files() {
 	done
 	echo
 
-	read -p "Are you sure you want to remove these files? Enter Y/N: " FIX_MACOS_FILES_YN
+	read -p "Are you sure you want to remove these files? [Y/n] " FIX_MACOS_FILES_YN
 	echo
-
-	[[ "${FIX_MACOS_FILES_YN}" != [Yy] ]] && output purple "No macOS attribute/Finder files under '${PWD}' removed" && return
+	[[ "${FIX_MACOS_FILES_YN}" == [Nn] ]] && output purple "No macOS attribute/Finder files under '${PWD}' removed" && return
 
 	for FILE in "${FILES_TO_REMOVE[@]}"; do
 		output yellow "Removing '${FILE}'"
@@ -1704,9 +1699,10 @@ _update_all() {
 	# Check 1st argument
 	if [[ "${1}" != "-y" ]]; then
 		# Check if they're sure
-		read -p "Are you sure? Enter Y/N: " UPDATE_YN
+		read -p "Are you sure? [Y/n] " UPDATE_YN
+		echo
 		# Exit if they're not
-		[[ "${UPDATE_YN}" != [Yy] ]] && output cyan "No updates performed" && return
+		[[ "${UPDATE_YN}" == [Nn] ]] && output cyan "No updates performed" && return
 	fi
 
 	# Bounce if we couldn't find a supported package manager
@@ -1876,8 +1872,9 @@ _update_cpan() {
 	# Check 1st argument
 	if [[ "${1}" != "-y" ]]; then
 		# Check if they're sure
-		read -p "Are you sure? Enter Y/N: " UPDATE_YN
-		[[ "${UPDATE_YN}" != [Yy] ]] && output cyan "update-cpan not performed" && return
+		read -p "Are you sure? [Y/n] " UPDATE_YN
+		echo
+		[[ "${UPDATE_YN}" == [Nn] ]] && output cyan "update-cpan not performed" && return
 	fi
 
 	# Bounce if we couldn't find a supported package manager
@@ -2105,9 +2102,9 @@ if [[ "${UNAME_KERNEL_NAME}" == "Darwin" ]]; then
 	# Reset all Office Mac 2011 files
 	_macos_repair_office() {
 		# Check if they're sure
-		read -p "Are you sure? Enter Y/N: " RESET_YN
-
-		[[ "${RESET_YN}" != [Yy] ]] && output purple "No changes" && return
+		read -p "Are you sure? [Y/n] " RESET_YN
+		echo
+		[[ "${RESET_YN}" == [Nn] ]] && output purple "No changes" && return
 
 		output red "Resetting all Microsoft Office data"
 		rm -rf                                                             \
@@ -2157,6 +2154,9 @@ if [[ "${UNAME_KERNEL_NAME}" == "Linux" ]]; then
 	alias kvm-undefine='_kvm_undefine'
 	alias kvm-watch='_kvm_watch'
 	alias sys-restart='_sys_restart'
+
+	# systemctl no-pager
+	hash systemctl && alias systemctl='systemctl --no-pager'
 
 	# Restart with systemctl
 	_sys_restart() {
@@ -2247,25 +2247,21 @@ if [[ "${UNAME_KERNEL_NAME}" == "Linux" ]]; then
 		local ARRAY_UNDEFINE=$(virsh list --all | awk '/'"${1}"'/ {print $2}')
 		[[ -z "${ARRAY_UNDEFINE}" ]] && output yellow "No VMs running matching search string '${1}'" && return
 
-		output purple "These VMs will be undefined:"
-		echo
-
+		output purple "These VMs will be undefined:"; echo
 		for VM in ${ARRAY_UNDEFINE[@]}; do
 			output red "${VM}"
 		done
 		echo
 
-		read -p "Are you sure? Enter Y/N: " UNDEFINE_YN
+		read -p "Are you sure? [Y/n] " UNDEFINE_YN
+		echo
+		[[ "${UNDEFINE_YN}" == [Nn] ]] && output purple "No VMs undefined" && return false
 
-		if [[ "${UNDEFINE_YN}" != [Yy] ]]; then
-			output purple "No VMs undefined"
-		else
-			for VM in ${ARRAY_UNDEFINE[@]}; do
-				output purple "Undefining '${VM}'"
-				virsh undefine ${VM}
-			done
-			echo
-		fi
+		for VM in ${ARRAY_UNDEFINE[@]}; do
+			output purple "Undefining '${VM}'"
+			virsh undefine ${VM}
+		done
+		echo
 	}
 
 	# Destroy all VMs
@@ -2273,25 +2269,21 @@ if [[ "${UNAME_KERNEL_NAME}" == "Linux" ]]; then
 		local ARRAY_DESTROY=($(virsh list | awk '/running/ {print $2}'))
 		[[ -z "${ARRAY_DESTROY}" ]] && output purple "No VMs running" && return
 
-		output purple "These VMs will be destroyed:"
-		echo
-
+		output purple "These VMs will be destroyed:"; echo
 		for VM in ${ARRAY_DESTROY[@]}; do
 			output red "${VM}"
 		done
 		echo
 
-		read -p "Are you sure? Enter Y/N: " DESTROY_YN
+		read -p "Are you sure? [Y/n] " DESTROY_YN
+		echo
+		[[ "${DESTROY_YN}" == [Nn] ]] && output purple "No VMs destroyed" && return false
 
-		if [[ "${DESTROY_YN}" != [Yy] ]]; then
-			output purple "No VMs destroyed"
-		else
-			for VM in ${ARRAY_DESTROY[@]}; do
-				output red "Destroying '${VM}'"
-				virsh destroy "${VM}"
-			done
-			echo
-		fi
+		for VM in ${ARRAY_DESTROY[@]}; do
+			output red "Destroying '${VM}'"
+			virsh destroy "${VM}"
+		done
+		echo
 	}
 
 	# Shutdown all VMs
@@ -2299,25 +2291,21 @@ if [[ "${UNAME_KERNEL_NAME}" == "Linux" ]]; then
 		local ARRAY_SHUTDOWN=($(virsh list | awk '/running/ {print $2}'))
 		[[ -z "${ARRAY_DESTROY}" ]] && output purple "No VMs running" && return
 
-		output purple "These VMs will be shutdown:"
-		echo
-
+		output purple "These VMs will be shutdown:"; echo
 		for VM in ${ARRAY_SHUTDOWN[@]}; do
 			output red "${VM}"
 		done
 		echo
 
-		read -p "Are you sure? Enter Y/N: " SHUTDOWN_YN
+		read -p "Are you sure? [Y/n] " SHUTDOWN_YN
+		echo
+		[[ "${SHUTDOWN_YN}" == [Nn] ]] && output purple "No VMs shutdown" && return false
 
-		if [[ "${SHUTDOWN_YN}" != [Yy] ]]; then
-			output purple "No VMs shutdown"
-		else
-			for VM in ${ARRAY_SHUTDOWN[@]}; do
-				output yellow "Shutting down VM '${VM}'"
-				virsh shutdown "${VM}"
-			done
-			echo
-		fi
+		for VM in ${ARRAY_SHUTDOWN[@]}; do
+			output yellow "Shutting down VM '${VM}'"
+			virsh shutdown "${VM}"
+		done
+		echo
 	}
 
 	# Start all VMs
@@ -2325,25 +2313,21 @@ if [[ "${UNAME_KERNEL_NAME}" == "Linux" ]]; then
 		local ARRAY_START=($(virsh list --all | awk '/shut off/ {print $2}' | sed -e '/Name/d' -e '/^$/d'))
 		[[ -z "${ARRAY_START}" ]] && output purple "No shut off VMs" && return
 
-		output purple "These VMs will be started:"
-		echo
-
+		output purple "These VMs will be started:"; echo
 		for VM in ${ARRAY_START[@]}; do
 			output green "${VM}"
 		done
 		echo
 
-		read -p "Are you sure? Enter Y/N: " START_YN
+		read -p "Are you sure? [Y/n] " START_YN
+		echo
+		[[ "${START_YN}" == [Nn] ]] && output purple "No VMs started" && return false
 
-		if [[ "${START_YN}" != [Yy] ]]; then
-			output purple "No VMs started"
-		else
-			for VM in ${ARRAY_START[@]}; do
-				output green "Starting VM '${VM}'"
-				virsh start "${VM}"
-			done
-			echo
-		fi
+		for VM in ${ARRAY_START[@]}; do
+			output green "Starting VM '${VM}'"
+			virsh start "${VM}"
+		done
+		echo
 	}
 
 fi
@@ -2437,6 +2421,9 @@ alias kk='ll'
 alias namp='nmap'
 alias pign='ping'
 alias tial='tail'
+
+# Alias to pass thru the 16mcolor hack over SSH
+[[ "${TERM}" == "xterm-16mcolor" ]] && alias ssh="TERM=${TERM} ssh"
 
 # If it has nmap binary:
 # only open ports, grepable output, aggressive and verbose aliases
