Update - Mon Nov 11 2019 22:15:48 -05:00 (EST)

diff --git a/.kdm/rc.d/net b/.kdm/rc.d/net
--- a/.kdm/rc.d/net
+++ b/.kdm/rc.d/net
@@ -18,29 +18,23 @@ _net_curl() {
 
 	while getopts "${OPTS}" OPT; do
 		case "${OPT}" in
-			h)
-				_net_curl_usage
-				;;
-			u)
-				URL="${OPTARG}"
-				;;
-			x)
-				CURL_PROXY="${OPTARG}"
-				;;
+			h) _net_curl_usage        ;;
+			u) URL="${OPTARG}"        ;;
+			x) CURL_PROXY="${OPTARG}" ;;
+
 			:)
 				output usage "ERROR: Option -${OPTARG} requires an argument"
 				echo
 				_net_curl_usage
 				;;
+
 			\?)
 				output usage "ERROR: Option -${OPTARG} is not a valid command line switch"
 				echo
 				_net_curl_usage
 				;;
-			*)
-				_net_curl_usage
-				break
-				;;
+
+			*) _net_curl_usage; break ;;
 		esac
 	done
 
@@ -107,7 +101,7 @@ _net_info() {
 # Python webserver
 _net_webserver() {
 	# Declare vars as local
-	local ARRAY_USAGE_OPTIONS USAGE_OPTIONS_STRING USAGE_STRING WEBSERVER_PID
+	local ARRAY_USAGE_OPTIONS USAGE_OPTIONS_STRING USAGE_STRING WEBSERVER_PID WEBSERVER_PORT
 
 	# Array of options
 	ARRAY_USAGE_OPTIONS=(
@@ -121,19 +115,29 @@ _net_webserver() {
 	USAGE_STRING="net-webserver <${USAGE_OPTIONS_STRING}>"
 	[[ -z "${1}" ]] && output usage "${USAGE_STRING}" && return
 
-	WEBSERVER_PID="$(pgrep -f 'SimpleHTTPServer' 2> /dev/null)"
+	WEBSERVER_PID="$(pgrep -f 'ComplexHTTPServer' 2> /dev/null)"
+
+	WEBSERVER_PORT="8192"
 
 	case "${1}" in
 		start)
 			if [[ "${WEBSERVER_PID}" ]]; then
-				output cyan "Webserver already running on port 8000"
+				output cyan "Webserver already running (PID ${WEBSERVER_PID})"
+				return
+			fi
+
+			# Check if ComplexHTTPServer is installed
+			if ! pip3 show ComplexHTTPServer > /dev/null 2>&1; then
+				output error "Python3 module 'ComplexHTTPServer' is not installed (try 'pip3 install ComplexHTTPServer')"
 				return
 			fi
 
 			# Start webserver
-			{ python -m SimpleHTTPServer &> /dev/null & disown; }
+			{ python3 -m ComplexHTTPServer "${WEBSERVER_PORT}" &> /dev/null & disown; }
 
-			output green "Webserver started on port 8000"
+			WEBSERVER_PID="$(pgrep -f 'ComplexHTTPServer' 2> /dev/null)"
+
+			output green "Webserver started (PID ${WEBSERVER_PID}) on port ${WEBSERVER_PORT}, serving directory '${PWD}'"
 			;;
 
 		stop)
@@ -142,8 +146,12 @@ _net_webserver() {
 				return
 			fi
 
-			kill -9 "${WEBSERVER_PID}"
-			output red "Webserver stopped"
+			if ! kill -9 "${WEBSERVER_PID}" 2> /dev/null; then
+				output error "Failed to kill -9 webserver (PID ${WEBSERVER_PID})"
+				return
+			fi
+
+			output red "Webserver (PID ${WEBSERVER_PID}) stopped"
 			;;
 	esac
 }
