Update (kdm-mbp-work-wl.z1) - 2022-12-12 10:58:56 -05:00 (Mon Dec 12 2022 10:58:56 AM EST)

diff --git a/.config/coc/extensions/install b/.config/coc/extensions/install
--- a/.config/coc/extensions/install
+++ b/.config/coc/extensions/install
@@ -1,45 +1,56 @@
 #!/usr/bin/env bash
 
-PKG_MANAGER="yarn"
+
+_method1() {
+	PKG_MANAGER="yarn"
+
+	ARRAY_DEPS=("${PKG_MANAGER}")
+
+	for DEP in "${ARRAY_DEPS[@]}"; do
+		if ! hash "${DEP}" > /dev/null 2>&1; then
+			echo "Command unavailable : '${DEP}', cannot continue"
+			exit 1
+		fi
+	done
+
+	CONCURRENCY="$(nproc)"
+
+	cd "${HOME}/.config/coc/extensions" || exit 2
+	echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions"
+	"${PKG_MANAGER}" install --ignore-engines --network-concurrency "${CONCURRENCY}" --non-interactive
+	echo; echo
+
+	cd "${HOME}/.config/coc/extensions/node_modules/coc-json" || exit 3
+	echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions/node_modules/coc-json"
+	rm -f ./package-lock.json > /dev/null 2>&1
+	"${PKG_MANAGER}" install --ignore-scripts --ignore-engines --network-concurrency "${CONCURRENCY}" --non-interactive
+	echo; echo
+
+	cd "${HOME}/.config/coc/extensions/node_modules/coc-yaml" || exit 4
+	echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions/node_modules/coc-yaml"
+	rm -f ./package-lock.json > /dev/null 2>&1
+	"${PKG_MANAGER}" install --ignore-scripts --ignore-engines --network-concurrency "${CONCURRENCY}" --non-interactive
+	echo; echo
+
+	cd "${HOME}/.vim/pack/kdm/coc.nvim" || exit 5
+	echo "Executing '${PKG_MANAGER} install' in ~/.vim/pack/kdm/coc.nvim"
+	rm -f ./package-lock.json > /dev/null 2>&1
+	"${PKG_MANAGER}" install --frozen-lockfile --network-concurrency "${CONCURRENCY}" --non-interactive
+	echo; echo
+
+	echo "Fixing coc-svg svgo dependency symlink"
+	ln -fs "${HOME}/.config/coc/extensions/node_modules/svgo" "${HOME}/.config/coc/extensions/node_modules/coc-svg/node_modules/svgo"
+	#echo;echo
+
+	#echo "Performing nvim CocUpdateSync"
+	#nvim -c 'CocUpdateSync|q'
+}
+
+_method2() {
+	cd "${HOME}/.config/coc/extensions" || exit 2
+	echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions"
+	npm install --install-strategy shallow --audit false --fund false --ignore-scripts --no-lockfile --omit=dev --legacy-peer-deps --no-global
+}
 
 
-ARRAY_DEPS=("${PKG_MANAGER}")
-
-for DEP in "${ARRAY_DEPS[@]}"; do
-	if ! hash "${DEP}" > /dev/null 2>&1; then
-		echo "Command unavailable : '${DEP}', cannot continue"
-		exit 1
-	fi
-done
-
-
-cd "${HOME}/.config/coc/extensions" || exit 2
-echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions"
-"${PKG_MANAGER}" install --ignore-engines --network-concurrency 8 --non-interactive
-echo; echo
-
-cd "${HOME}/.config/coc/extensions/node_modules/coc-json" || exit 3
-echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions/node_modules/coc-json"
-rm -f ./package-lock.json > /dev/null 2>&1
-"${PKG_MANAGER}" install --ignore-scripts --ignore-engines --network-concurrency "$(nproc)" --non-interactive
-echo; echo
-
-cd "${HOME}/.config/coc/extensions/node_modules/coc-yaml" || exit 4
-echo "Executing '${PKG_MANAGER} install' in ~/.config/coc/extensions/node_modules/coc-yaml"
-rm -f ./package-lock.json > /dev/null 2>&1
-"${PKG_MANAGER}" install --ignore-scripts --ignore-engines --network-concurrency "$(nproc)" --non-interactive
-echo; echo
-
-cd "${HOME}/.vim/pack/kdm/coc.nvim" || exit 5
-echo "Executing '${PKG_MANAGER} install' in ~/.vim/pack/kdm/coc.nvim"
-rm -f ./package-lock.json > /dev/null 2>&1
-"${PKG_MANAGER}" install --frozen-lockfile --network-concurrency "$(nproc)" --non-interactive
-echo; echo
-
-echo "Fixing coc-svg svgo dependency symlink"
-ln -fs "${HOME}/.config/coc/extensions/node_modules/svgo" "${HOME}/.config/coc/extensions/node_modules/coc-svg/node_modules/svgo"
-#echo;echo
-
-
-#echo "Performing nvim CocUpdateSync"
-#nvim -c 'CocUpdateSync|q'
+_method2
